# Google Drive ID of the cards spreadsheet
sheet_gdid: ***

# Spreadsheet type, either "xlsm" or "xlsx"
sheet_type: xlsm

# Local path to the artwork folder
artwork_path: C:\Google Drive\Artwork\

# Path to GIMP console executable
gimp_console_path: C:\Program Files\GIMP 2\bin\gimp-console-2.10.exe

# Path to ImageMagick executable
magick_path: C:\Program Files\ImageMagick-7.0.10-Q16-HDRI\magick.exe

# Path to OCTGN destination folder (may be empty)
octgn_destination_path: C:\Google Drive\OCTGN\

# Whether to generate all cards from scratch (true)
# or update only the cards, changed since the previous script run (false)
from_scratch: true

# Number of parallel processes to use ("default" means "cpu_count() - 1")
parallelism: default

# List of set IDs to work on
set_ids:
  - 8a3273ca-1ccd-4e07-913b-766fcc49fe6f
  - 17b90ca1-7e3e-4891-99da-954a7833e88e

# List of languages
languages:
  - English
  - German
  - Spanish

# List of outputs
outputs:
  - db
  - octgn
  - pdf
  - makeplayingcards_zip
  - makeplayingcards_7z
  - drivethrucards_zip
  - drivethrucards_7z